[package]
name = "rserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
dunce = "1.0.2"
crossbeam = "0.8"
lazy_static = "1.4.0"
